# Mô hình Hồi quy tuyến tính

- Với 1 tập dữ liệu cho sẵn:
    + x = [2,3,7,8,11]
    + y = [1,3,2,6,5]
- sử dụng mô hình hồi quy để dự đoán y(9) ~= ?

### Cách 1 : sử dụng gói numpy

In [91]:
import numpy as np

In [92]:
# tập dữ liệu mẫu
X = [2,3,7,8,11]
Y = [1,3,2,6,5]

In [93]:
A = np.zeros(shape=(2,2))
A

array([[0., 0.],
       [0., 0.]])

In [94]:
B = np.zeros(shape=(2,))

In [95]:
for x, y in zip(X, Y):
    A[0, 0] += x**2 
    A[0, 1] += x
    B[0] += y*x
    B[1] += y

A[1,0] = A[0,1]
A[1,1] = len(X) 

A


array([[247.,  31.],
       [ 31.,   5.]])

In [96]:
B

array([128.,  17.])

In [97]:
np.linalg.solve(A, B)

array([0.41240876, 0.84306569])

### Cách 2 : giải tối ưu có điều kiện với gói scipy

In [98]:
from scipy.optimize import minimize

In [99]:
def loss(v):
    L = 0
    for x, y in zip(X, Y):
        L += (v[0]*x + v[1] - y)**2
    return L

In [100]:
def gradient(v):
    g = [0,0]
    for x, y in zip(X, Y):
        g[0] = (v[0]*x + v[1] -y)*x
        g[1] = v[0]*x + v[1] -y
    g = 2*g
    return g

In [101]:
minimize(loss,[0,0])

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 7.87956204379565
        x: [ 4.124e-01  8.431e-01]
      nit: 2
      jac: [ 3.576e-07 -7.153e-07]
 hess_inv: [[ 1.761e-02 -1.239e-01]
            [-1.239e-01  9.844e-01]]
     nfev: 15
     njev: 5

### Cách 3: dùng tool

In [102]:
from sympy import *

In [103]:
a, b = symbols('a b')
v = [a, b]
loss(v)

(2*a + b - 1)**2 + (3*a + b - 3)**2 + (7*a + b - 2)**2 + (8*a + b - 6)**2 + (11*a + b - 5)**2

In [104]:
loss(v).expand()

247*a**2 + 62*a*b - 256*a + 5*b**2 - 34*b + 75

In [108]:
X = np.array(X)
X = X.reshape(-1, 1)

Y = np.array(Y)


In [109]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, Y)

model.coef_ , model.intercept_

(array([0.41240876]), np.float64(0.8430656934306566))

In [110]:
model.predict([[9]])

array([4.55474453])

### Cách 4 : Giải trực tiếp

#### Xây dựng hàm loss
- L = (X * tetal - Y).T * (X * tetal - Y)

In [115]:
X = [2,3,7,8,11]
Y = [1,3,2,6,5]

X = np.expand_dims(X , axis=1)
Xs = np.concatenate((X, np.ones_like(X)), axis=1)

Xs

array([[ 2,  1],
       [ 3,  1],
       [ 7,  1],
       [ 8,  1],
       [11,  1]])

In [116]:
Ys = np.expand_dims(Y , axis=1)

Ys

array([[1],
       [3],
       [2],
       [6],
       [5]])

In [117]:
np.linalg.inv((Xs.T).dot(Xs)).dot(Xs.T).dot(Ys)

array([[0.41240876],
       [0.84306569]])